[package]
name = "feature"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["feature3"]
feature1 = []
feature2 = []
feature3 = []


[dependencies]
